#!/bin/bash


ROOTDIR=/yumrepo/7

download_files() {
	echo "start download $* ..."
	test ! -d $ROOTDIR && mkdir -p $ROOTDIR
	yum install -y --nogpgcheck --downloadonly --downloaddir=$ROOTDIR $*
	echo "finish download $* ."
	createrepo $ROOTDIR
}

download_files $*

